# SECTION 1: IMPORT LIBRARIES & LOAD DATA
_________________________________________

In [2]:
import pandas as pd
import numpy as np

In [3]:
customer = pd.read_csv('olist_customers_dataset.csv')
geolocation = pd.read_csv('olist_geolocation_dataset.csv')
order_items = pd.read_csv('olist_order_items_dataset.csv')
order_payments = pd.read_csv('olist_order_payments_dataset.csv')
order_reviews = pd.read_csv('olist_order_reviews_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
sellers = pd.read_csv('olist_sellers_dataset.csv')
category_name_translation = pd.read_csv('product_category_name_translation.csv')

In [4]:
print(orders['order_status'].value_counts())
print()
print(orders.isnull().sum())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [5]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [6]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

#

# SECTION 2: TARGET VARIABLE CONSTRUCTION
________________

In [7]:
orders_delivered = orders[orders['order_status'] == 'delivered'].copy()

In [8]:
orders_delivered['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders_delivered['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])
orders_delivered['is_late'] = (orders_delivered['order_delivered_customer_date'] > orders_delivered['order_estimated_delivery_date']).astype(int)

In [9]:
orders_delivered

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0

#
# SECTION 3: JOIN PIPELINE
___

In [10]:
# ORDER ITEMS AGG
# One order can have multiple items → collapse to one row per order
order_items_agg = order_items.groupby('order_id').agg(
    num_items=('order_item_id', 'count'),        
    total_price=('price', 'sum'),                
    total_freight=('freight_value', 'sum')       
).reset_index()

# ORDER PAYMENTS AGG
# One order can have multiple payments (e.g. split payment) → collapse to one row
order_payments_agg = order_payments.groupby('order_id').agg(
    payment_installments=('payment_installments', 'max'),       
    total_payment_value=('payment_value', 'sum'),               
    payment_type=('payment_type', lambda x: x.mode()[0])       
).reset_index()

In [11]:
# Rebuild df cleanly
df = orders_delivered.merge(customer, on='customer_id', how='inner')
print(f"Shape after customers join: {df.shape}")

df = df.merge(order_items_agg, on='order_id', how='left')
print(f"Shape after order_items join: {df.shape}")

df = df.merge(order_payments_agg, on='order_id', how='left')
print(f"Shape after payments join: {df.shape}")

# Deduplicated reviews
reviews_clean = order_reviews.sort_values('review_creation_date', ascending=False)\
                              .drop_duplicates(subset='order_id', keep='first')\
                              [['order_id', 'review_score']]

df = df.merge(reviews_clean, on='order_id', how='left')
print(f"Shape after reviews join: {df.shape}")

Shape after customers join: (96478, 13)
Shape after order_items join: (96478, 16)
Shape after payments join: (96478, 19)
Shape after reviews join: (96478, 20)

In [12]:
order_product = order_items.groupby('order_id')['product_id'].agg(lambda x:x.mode()[0]).reset_index()
df = df.merge(order_product,on='order_id',how='left')
df = df.merge(products,on='product_id',how='left')
print(f"Shape after products join: {df.shape}")

Shape after products join: (96478, 29)

In [13]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [14]:
order_seller = order_items.groupby('order_id')['seller_id'].agg(lambda x:x.mode()[0]).reset_index()
df = df.merge(order_seller, on='order_id', how='left')
df = df.merge(sellers, on='seller_id', how='left')
print(f"Shape after sellers join: {df.shape}")

Shape after sellers join: (96478, 33)

In [15]:
df = df.merge(category_name_translation, on='product_category_name', how='left')
print(f"Shape after category translation join: {df.shape}")

Shape after category translation join: (96478, 34)

In [16]:
print(f"Shape after category translation join: {df.shape}")

Shape after category translation join: (96478, 34)

#
# SECTION 4: DATA CLEANING
___

In [17]:
df.isnull().sum()[df.isnull().sum() > 0]

order_approved_at                  14
order_delivered_carrier_date        2
order_delivered_customer_date       8
payment_installments                1
total_payment_value                 1
payment_type                        1
review_score                      646
product_category_name            1361
product_name_lenght              1361
product_description_lenght       1361
product_photos_qty               1361
product_weight_g                   16
product_length_cm                  16
product_height_cm                  16
product_width_cm                   16
product_category_name_english    1381
dtype: int64

In [18]:
cols_to_drop = ['order_approved_at',
    'order_delivered_carrier_date', 
    'order_delivered_customer_date',
    'payment_installments',
    'total_payment_value',
    'payment_type']
df = df.dropna(subset=cols_to_drop)
df['review_score'] = df['review_score'].fillna(df['review_score'].median())
df['product_category_name'] = df['product_category_name'].fillna('unknown')

for col in ['product_name_lenght', 'product_description_lenght', 
            'product_photos_qty', 'product_weight_g',
            'product_length_cm', 'product_height_cm', 'product_width_cm']:
    df[col] = df[col].fillna(df[col].median())
    
print(f"Remaining nulls: {df.isnull().sum().sum()}")
print(f"Final shape: {df.shape}")

Remaining nulls: 1380
Final shape: (96454, 34)

In [19]:
df.isnull().sum()[df.isnull().sum() > 0]

product_category_name_english    1380
dtype: int64

In [20]:
df['product_category_name_english'] = df['product_category_name_english'].fillna('unknown')

# Confirm
print(f"Remaining nulls: {df.isnull().sum().sum()}")
print(f"Final shape: {df.shape}")

Remaining nulls: 0
Final shape: (96454, 34)

In [21]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'is_late', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'num_items', 'total_price',
       'total_freight', 'payment_installments', 'total_payment_value',
       'payment_type', 'review_score', 'product_id', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'seller_id',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english'],
      dtype='object')

In [22]:
cols_to_drop = ['order_id','customer_id','order_status','product_category_name']
df = df.drop(columns=cols_to_drop)

In [23]:
print(f"Shape after dropping useless columns: {df.shape}")
print(df.columns.tolist())

Shape after dropping useless columns: (96454, 30)
['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'is_late', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'num_items', 'total_price', 'total_freight', 'payment_installments', 'total_payment_value', 'payment_type', 'review_score', 'product_id', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state', 'product_category_name_english']

#
#  SECTION 5: EXPLORATORY DATA ANALYSIS (EDA)
___

In [24]:
import plotly.express as px

In [25]:
df

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_id,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,...,4.0,500.0,19.0,8.0,13.0,3504c0cb71d7fa48d967e0e4c94d59d9,9350,maua,SP,housewares
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,...,1.0,400.0,19.0,13.0,19.0,289cdb325fb7e7f891c38608bf9e0962,31570,belo horizonte,SP,perfumery
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,...,1.0,420.0,24.0,19.0,21.0,4869f7a5dfa277a7dca6462dcf3b52b2,14840,guariba,SP,auto
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,...,3.0,450.0,30.0,10.0,20.0,66922902710d126a0e7d26b0e3805106,31842,belo horizonte,MG,pet_shop
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,...,4.0,250.0,51.0,15.0,15.0,2c9e548be18521d1c43cde1c582c6de8,8752,mogi das cruzes,SP,stationery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,...,1.0,1175.0,22.0,13.0,18.0,e24fc9fcd865784fb25705606fe3dfe7,12913,braganca paulista,SP,health_beauty
96474,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,...,4.0,4950.0,40.0,10.0,40.0,1f9ab4708f3056ede07124aad39a2554,17602,tupa,SP,baby
96475,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,...,2.0,13300.0,32.0,90.0,22.0,d50d79cb34e38265a8649c383dcffd48,8290,sao paulo,SP,home_appliances_2
96476,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,...,1.0,6550.0,20.0,20.0,20.0,a1043bafd471dff536d0c462352beb48,37175,ilicinea,MG,computers_accessories
96477,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,...,1.0,150.0,16.0,7.0,15.0,ececbfcff9804a2d6b40f589df8eef2b,14407,franca,SP,health_beauty

In [26]:
state_late = df.groupby('customer_state')['is_late'].mean().sort_values(ascending=False).reset_index()
state_late.columns = ['customer_state', 'late_rate']
state_late['late_rate'] = round(state_late['late_rate'] * 100,2)
fig = px.bar(
    state_late,
    x='customer_state',
    y='late_rate',
    title='Late Delivery Rate by Customer State',
    color='late_rate',
    color_continuous_scale='Reds',
    labels={'late_rate': 'Late Rate (%)', 'customer_state': 'State'}
)
fig.show()

In [27]:
category_late = df.groupby('product_category_name_english')['is_late'].mean().sort_values(ascending=False).head(15).reset_index()
category_late.columns = ['category','late_rate']
category_late['late_rate'] = round(category_late['late_rate'] * 100, 2)

fig = px.bar(category_late,
             x='late_rate',
             y='category',
             title='Top 15 Product Categories by Late Delivery Rate',
             orientation='h',
             color='late_rate',
             color_continuous_scale='Reds',
             labels={'late_rate': 'Late Rate (%)', 'category': 'Category'})
fig.update_layout(yaxis={'categoryorder' : 'total ascending'})
fig.show()

In [28]:
df.dtypes

order_purchase_timestamp                 object
order_approved_at                        object
order_delivered_carrier_date             object
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
is_late                                   int64
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
num_items                                 int64
total_price                             float64
total_freight                           float64
payment_installments                    float64
total_payment_value                     float64
payment_type                             object
review_score                            float64
product_id                               object
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
seller_id                                object
seller_zip_code_prefix                    int64
seller_city                              object
seller_state                             object
product_category_name_english            object
dtype: object

In [29]:
df['order_month'] = pd.to_datetime(df['order_purchase_timestamp']).dt.to_period('M').astype(str)
time_late = df.groupby('order_month')['is_late'].mean().reset_index()
time_late.columns = ['month', 'late_rate']
time_late['late_rate'] = round(time_late['late_rate']* 100,2)

fig = px.line(time_late,
              x='month',
              y='late_rate',
              title='Late Delivery Rate Over Time',
              labels={'late_rate': 'Late Rate (%)', 'month': 'Month'})
fig.update_xaxes(tickangle=45)
fig.show()

In [30]:
df['review_score'].value_counts()

review_score
5.0    57380
4.0    18890
1.0     9350
3.0     7915
2.0     2919
Name: count, dtype: int64

In [31]:
review_late = df.groupby('is_late')['review_score'].mean().reset_index()
review_late['is_late'] = review_late['is_late'].map({0 : 'On Time', 1 : 'Late'})
fig = px.bar(review_late,
             x='is_late',
             y='review_score',
             title='Average Review Score: Late vs On Time Deliveries',
             color='is_late',
             color_discrete_map={'On Time' : 'Green', 'Late' : 'Red'},
             labels={'review_score': 'Avg Review Score', 'is_late': 'Delivery Status'})
fig.show()

In [32]:
fig = px.box(df,
             x='is_late',
             y='product_weight_g',
             color='is_late',
             color_discrete_map={0 : 'Green',1 : 'Red'},
             labels={'product_weight_g' : 'Product Weight (g)', 'is_late': 'Is Late'})
fig.update_layout(yaxis_range=[0,20000])
fig.show()

In [33]:
df

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_id,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,order_month
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,...,500.0,19.0,8.0,13.0,3504c0cb71d7fa48d967e0e4c94d59d9,9350,maua,SP,housewares,2017-10
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,...,400.0,19.0,13.0,19.0,289cdb325fb7e7f891c38608bf9e0962,31570,belo horizonte,SP,perfumery,2018-07
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,...,420.0,24.0,19.0,21.0,4869f7a5dfa277a7dca6462dcf3b52b2,14840,guariba,SP,auto,2018-08
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,...,450.0,30.0,10.0,20.0,66922902710d126a0e7d26b0e3805106,31842,belo horizonte,MG,pet_shop,2017-11
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,...,250.0,51.0,15.0,15.0,2c9e548be18521d1c43cde1c582c6de8,8752,mogi das cruzes,SP,stationery,2018-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,...,1175.0,22.0,13.0,18.0,e24fc9fcd865784fb25705606fe3dfe7,12913,braganca paulista,SP,health_beauty,2017-03
96474,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,...,4950.0,40.0,10.0,40.0,1f9ab4708f3056ede07124aad39a2554,17602,tupa,SP,baby,2018-02
96475,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,...,13300.0,32.0,90.0,22.0,d50d79cb34e38265a8649c383dcffd48,8290,sao paulo,SP,home_appliances_2,2017-08
96476,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,...,6550.0,20.0,20.0,20.0,a1043bafd471dff536d0c462352beb48,37175,ilicinea,MG,computers_accessories,2018-01
96477,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,...,150.0,16.0,7.0,15.0,ececbfcff9804a2d6b40f589df8eef2b,14407,franca,SP,health_beauty,2018-03

In [34]:
seller_late = df.groupby('seller_state')['is_late'].mean().sort_values(ascending=False).reset_index()
seller_late.columns = ['sellers_state','late_rate']
seller_late['late_rate'] = round(seller_late['late_rate'] * 100,2) 

fig = px.bar(seller_late,
             x='sellers_state',
             y='late_rate',
             title='Late Delivery Rate by Seller State',
             color='late_rate',
             color_continuous_scale='Reds',
             labels={'late_rate' : 'Late Rate (%)','seller_state': 'Seller State'})
fig.show()

In [35]:
df

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_id,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,order_month
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,...,500.0,19.0,8.0,13.0,3504c0cb71d7fa48d967e0e4c94d59d9,9350,maua,SP,housewares,2017-10
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,...,400.0,19.0,13.0,19.0,289cdb325fb7e7f891c38608bf9e0962,31570,belo horizonte,SP,perfumery,2018-07
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,...,420.0,24.0,19.0,21.0,4869f7a5dfa277a7dca6462dcf3b52b2,14840,guariba,SP,auto,2018-08
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,...,450.0,30.0,10.0,20.0,66922902710d126a0e7d26b0e3805106,31842,belo horizonte,MG,pet_shop,2017-11
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,...,250.0,51.0,15.0,15.0,2c9e548be18521d1c43cde1c582c6de8,8752,mogi das cruzes,SP,stationery,2018-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,...,1175.0,22.0,13.0,18.0,e24fc9fcd865784fb25705606fe3dfe7,12913,braganca paulista,SP,health_beauty,2017-03
96474,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,...,4950.0,40.0,10.0,40.0,1f9ab4708f3056ede07124aad39a2554,17602,tupa,SP,baby,2018-02
96475,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,...,13300.0,32.0,90.0,22.0,d50d79cb34e38265a8649c383dcffd48,8290,sao paulo,SP,home_appliances_2,2017-08
96476,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,...,6550.0,20.0,20.0,20.0,a1043bafd471dff536d0c462352beb48,37175,ilicinea,MG,computers_accessories,2018-01
96477,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,...,150.0,16.0,7.0,15.0,ececbfcff9804a2d6b40f589df8eef2b,14407,franca,SP,health_beauty,2018-03

In [36]:
cat_analysis = df.groupby('product_category_name_english').agg(late_rate =('is_late','mean'),
                                                               total_revenue =('total_price','sum'),
                                                               order_count =('is_late','count')).reset_index()
cat_analysis['late_rate'] = round(cat_analysis['late_rate'] * 100,2)
cat_analysis = cat_analysis[cat_analysis['order_count'] >= 100]
fig = px.scatter(cat_analysis,
                 x='total_revenue',
                 y='late_rate',
                 size='order_count',
                 hover_name='product_category_name_english',
                 title='Category Revenue vs Late Delivery Rate',
                 labels={'total_revenue': 'Total Revenue (R$)',
                         'late_rate': 'Late Rate (%)',
                         'order_count': 'Order Count'},
                 color='late_rate',
                 color_continuous_scale='Reds')
fig.show()

#
# SECTION 6: MACHINE LEARNING
___

In [37]:
df.dtypes

order_purchase_timestamp                 object
order_approved_at                        object
order_delivered_carrier_date             object
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
is_late                                   int64
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
num_items                                 int64
total_price                             float64
total_freight                           float64
payment_installments                    float64
total_payment_value                     float64
payment_type                             object
review_score                            float64
product_id                               object
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
seller_id                                object
seller_zip_code_prefix                    int64
seller_city                              object
seller_state                             object
product_category_name_english            object
order_month                              object
dtype: object

In [38]:
for i in ['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_estimated_delivery_date']:
    df[i] = pd.to_datetime(df[i])

In [39]:
df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_estimated_delivery_date']]

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-18
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-13
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-09-04
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-15
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-26
...,...,...,...,...
96473,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-28
96474,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-03-02
96475,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-27
96476,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-02-15
96477,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-04-03

In [40]:
df['approval_time'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.total_seconds() / 3600
df['shipping_time'] = (df['order_delivered_carrier_date'] - df['order_approved_at']).dt.total_seconds() / 3600
df['estimated_delivery_days'] = (df['order_estimated_delivery_date'] - df['order_purchase_timestamp']).dt.total_seconds() / 3600 / 24
df['purchase_month'] = pd.to_datetime(df['order_purchase_timestamp']).dt.month
df['purchase_dayofweek'] = pd.to_datetime(df['order_purchase_timestamp']).dt.day_of_week

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn import set_config
set_config(display='text')

In [42]:
df.columns

Index(['order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'is_late', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'num_items', 'total_price', 'total_freight', 'payment_installments',
       'total_payment_value', 'payment_type', 'review_score', 'product_id',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'seller_id',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english', 'order_month', 'approval_time',
       'shipping_time', 'estimated_delivery_days', 'purchase_month',
       'purchase_dayofweek'],
      dtype='object')

In [43]:
cols_to_drop = ['order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date','customer_unique_id','customer_city','seller_city',
       'product_id', 'seller_id','order_month']

df_ml = df.drop(columns=cols_to_drop,errors='ignore')
cat_cols = ['customer_state', 'seller_state', 'payment_type', 'product_category_name_english']
le = LabelEncoder()
for col in cat_cols:
    df_ml[col] = le.fit_transform(df_ml[col].astype(str))
    
x = df_ml.drop(columns='is_late')
y = df_ml['is_late']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

print(f"X_train shape: {x_train.shape}")
print(f"X_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (77163, 24)
X_test shape: (19291, 24)
y_train shape: (77163,)
y_test shape: (19291,)

In [44]:
rf = RandomForestClassifier(n_estimators=100,random_state=42,class_weight='balanced')
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96     17674
           1       0.67      0.43      0.52      1617

    accuracy                           0.93     19291
   macro avg       0.81      0.71      0.74     19291
weighted avg       0.93      0.93      0.93     19291

In [45]:
feature_importance = pd.DataFrame({'Feature' : x_train.columns ,
                                   'importance' : rf.feature_importances_}).sort_values('importance',ascending=False)

In [46]:
fig = px.bar(feature_importance.head(10),
             x='importance',
             y='Feature',
             orientation='h',
             title='Top 10 Feature Importances — Late Delivery Prediction',
             color='importance')
fig.update_layout(yaxis={'categoryorder' : 'total ascending'})
fig.show()

In [47]:
x = df_ml.drop(columns=['is_late','review_score'])
y = df_ml['is_late']

X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2,random_state=42)
rf2 = RandomForestClassifier(n_estimators=100,random_state=42,class_weight='balanced')
rf2.fit(X_train,Y_train)
Y_pred = rf2.predict(X_test)
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.93      0.98      0.96     17674
           1       0.56      0.23      0.33      1617

    accuracy                           0.92     19291
   macro avg       0.74      0.61      0.64     19291
weighted avg       0.90      0.92      0.90     19291

In [48]:
feature_importance2 = pd.DataFrame({'feature' : X_train.columns,
                                    'importance' : rf2.feature_importances_}).sort_values('importance',ascending=False)
fig = px.bar(feature_importance2.head(10),
             x='importance',
             y='feature',
             orientation='h',
             title='Top 10 Feature Importances — Late Delivery Prediction (Clean)',
             color='importance')
fig.update_layout(yaxis={'categoryorder' : 'total ascending'})
fig.show()

In [49]:
df

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,...,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,order_month,approval_time,shipping_time,estimated_delivery_days,purchase_month,purchase_dayofweek
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,...,9350,maua,SP,housewares,2017-10,0.178333,56.795833,15.544063,10,0
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,...,31570,belo horizonte,SP,perfumery,2018-07,30.713889,11.109167,19.137766,7,1
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,...,14840,guariba,SP,auto,2018-08,0.276111,4.910278,26.639711,8,2
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,...,31842,belo horizonte,MG,pet_shop,2017-11,0.298056,89.900000,26.188819,11,5
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,...,8752,mogi das cruzes,SP,stationery,2018-02,1.030556,21.434722,12.112049,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,...,12913,braganca paulista,SP,health_beauty,2017-03,0.000000,25.399444,18.587442,3,3
96474,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,...,17602,tupa,SP,baby,2018-02,0.194167,34.201389,23.459051,2,1
96475,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,...,8290,sao paulo,SP,home_appliances_2,2017-08,0.292500,29.802778,30.384225,8,6
96476,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,...,37175,ilicinea,MG,computers_accessories,2018-01,0.131667,89.978333,37.105243,1,0
96477,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,...,14407,franca,SP,health_beauty,2018-03,14.382778,10.858611,25.126736,3,3

#
# EXPORT CSV
___

In [58]:
state_mapping = {
    'AC': 'Acre', 'AL': 'Alagoas', 'AM': 'Amazonas', 'AP': 'Amapá',
    'BA': 'Bahia', 'CE': 'Ceará', 'DF': 'Distrito Federal', 'ES': 'Espírito Santo',
    'GO': 'Goiás', 'MA': 'Maranhão', 'MG': 'Minas Gerais', 'MS': 'Mato Grosso do Sul',
    'MT': 'Mato Grosso', 'PA': 'Pará', 'PB': 'Paraíba', 'PE': 'Pernambuco',
    'PI': 'Piauí', 'PR': 'Paraná', 'RJ': 'Rio de Janeiro', 'RN': 'Rio Grande do Norte',
    'RO': 'Rondônia', 'RR': 'Roraima', 'RS': 'Rio Grande do Sul', 'SC': 'Santa Catarina',
    'SE': 'Sergipe', 'SP': 'São Paulo', 'TO': 'Tocantins'
}

df['customer_state_name'] = df['customer_state'].map(state_mapping)
df['seller_state_name'] = df['seller_state'].map(state_mapping)
df['country'] = 'Brazil'

df['weight_group'] = pd.cut(df['product_weight_g'],
                             bins=[0, 500, 1000, 5000, 10000, 50000],
                             labels=['0-500g', '500g-1kg', '1-5kg', '5-10kg', '10kg+'])

df.to_csv('olist_final.csv', index=False)
print("Re-exported successfully")

Re-exported successfully

In [60]:
df

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,...,order_month,approval_time,shipping_time,estimated_delivery_days,purchase_month,purchase_dayofweek,country,customer_state_name,seller_state_name,weight_group
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,...,2017-10,0.178333,56.795833,15.544063,10,0,Brazil,São Paulo,São Paulo,0-500g
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,...,2018-07,30.713889,11.109167,19.137766,7,1,Brazil,Bahia,São Paulo,0-500g
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,...,2018-08,0.276111,4.910278,26.639711,8,2,Brazil,Goiás,São Paulo,0-500g
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,...,2017-11,0.298056,89.900000,26.188819,11,5,Brazil,Rio Grande do Norte,Minas Gerais,0-500g
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,...,2018-02,1.030556,21.434722,12.112049,2,1,Brazil,São Paulo,São Paulo,0-500g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,...,2017-03,0.000000,25.399444,18.587442,3,3,Brazil,São Paulo,São Paulo,1-5kg
96474,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,...,2018-02,0.194167,34.201389,23.459051,2,1,Brazil,São Paulo,São Paulo,1-5kg
96475,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,...,2017-08,0.292500,29.802778,30.384225,8,6,Brazil,Bahia,São Paulo,10kg+
96476,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,...,2018-01,0.131667,89.978333,37.105243,1,0,Brazil,Rio de Janeiro,Minas Gerais,5-10kg
96477,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,...,2018-03,14.382778,10.858611,25.126736,3,3,Brazil,Paraná,São Paulo,0-500g